### ISSUE TITLE
prepare_data/step2_detection.sh

### ISSUE THREAD

**Issue by CherishineNi** [Yu-Wu/Decoupled-Novel-Object-Captioner#1]
当我运行 python extract_detection_feature.py后出现如下错误：
![2019-03-25 20-45-06屏幕截图](https://user-images.githubusercontent.com/44666138/54920990-9b62fb00-4f3f-11e9-93ae-196c680356fe.png)

tensorflow是1.4.1的gpu版本
该如何解决？

**Comment by CherishineNi** [comment]
/usr/bin/python3.5 /home/team/Zzz/Decoupled-Novel-Object-Captioner-master/prepare_data/utils/detection/models/research/extract_detection_feature.py
Need to Detect: 123287 Images.
Found existing dir in /home/team/visualconcepts/data/extracted_object_memory
2019-03-25 20:44:26.018234: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-25 20:44:26.157080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 11.54GiB
2019-03-25 20:44:26.276331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 11.91GiB freeMemory: 11.74GiB
2019-03-25 20:44:26.277316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2019-03-25 20:44:26.277346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 
2019-03-25 20:44:26.277353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y 
2019-03-25 20:44:26.277356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y 
2019-03-25 20:44:26.277363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-03-25 20:44:26.277367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
  0%|          | 0/123287 [00:00<?, ?it/s]2019-03-25 20:44:29.699065: E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
2019-03-25 20:44:29.699108: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team/Zzz/Decoupled-Novel-Object-Captioner-master/prepare_data/utils/detection/models/research/extract_detection_feature.py", line 171, in <module>
    main()    
  File "/home/team/Zzz/Decoupled-Novel-Object-Captioner-master/prepare_data/utils/detection/models/research/extract_detection_feature.py", line 158, in main
    feed_dict={image_tensor: image_np_expanded})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]

Caused by op 'Preprocessor/map/TensorArray', defined at:
  File "/home/team/Zzz/Decoupled-Novel-Object-Captioner-master/prepare_data/utils/detection/models/research/extract_detection_feature.py", line 171, in <module>
    main()
  File "/home/team/Zzz/Decoupled-Novel-Object-Captioner-master/prepare_data/utils/detection/models/research/extract_detection_feature.py", line 123, in main
    tf.import_graph_def(coco_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]

**Comment by Yu-Wu** [comment]
@CherishineNi 

Thanks for your interest in our paper.

Based on the provided log, the main reason is the mismatched TensorFlow Version for detection. 
Due to the TensorFlow Object Detection API, the code might be not able to run at TF1.4.1.

I am trying to fix it in TF 1.4.1, but it may takes several days.
Currently, could you please **try a newer TF version** (such as TF 1.10) ?

**Comment by CherishineNi** [comment]
> @CherishineNi
> 
> Thanks for your interest in our paper.
> 
> Based on the provided log, the main reason is the mismatched TensorFlow Version for detection.
> Due to the TensorFlow Object Detection API, the code might be not able to run at TF1.4.1.
> 
> I am trying to fix it in TF 1.4.1, but it may takes several days.
> Currently, could you please **try a newer TF version** (such as TF 1.10) ?

my experiment is cuda8.0+cudnn6.0 ，I  have tried updated TF to TF 1.6.0 but failed, because it needs cuda9

**Comment by Yu-Wu** [comment]
@CherishineNi 

I checked the TensorFlow Object Detection API (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) and found the following instructions:

_Our frozen inference graphs are generated using the v1.12.0 release version of Tensorflow and we do not guarantee that these will work with other versions; this being said, each frozen inference graph can be regenerated using your current version of Tensorflow by re-running the exporter, pointing it at the model directory as well as the corresponding config file in samples/configs._


It seems it is not easy to run it under Cuda8.0. Could you please update the coda version and the TensorFlow version?

Alternatively, if you could access the Google Drive, I uploaded the pre-extracted detection results (about 5 G) via Google Drive.

Download link:
https://drive.google.com/open?id=1zit11UTSTQl00ynsyhSlF0NtggHSQmwI

**Comment by CherishineNi** [comment]
> @CherishineNi
> 
> I checked the TensorFlow Object Detection API (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) and found the following instructions:
> 
> _Our frozen inference graphs are generated using the v1.12.0 release version of Tensorflow and we do not guarantee that these will work with other versions; this being said, each frozen inference graph can be regenerated using your current version of Tensorflow by re-running the exporter, pointing it at the model directory as well as the corresponding config file in samples/configs._
> 
> It seems it is not easy to run it under Cuda8.0. Could you please update the coda version and the TensorFlow version?
> 
> Alternatively, if you could access the Google Drive, I uploaded the pre-extracted detection results (about 5 G) via Google Drive.
> 
> Download link:
> https://drive.google.com/open?id=1fAifJqdNv7scJ-lNave1WDLdNO-V4pGB

Thank you for your suggestion! 
But now I want to train on my own dataset ( including 2000 images and every image has 5 captions like COCO). 
I have used yolo3 of this project on https://github.com/qqwweee/keras-yolo3 to detect my objects(just 3 classes). And then I want to use your methods to generate image caption, but now I don't know what to do next. Could you please tell me what should I do next ?

**Comment by Yu-Wu** [comment]
@CherishineNi 

Sorry that I did catch the point. Are you going to train a DNOC captioning model on your OWN data?

To do this, you might first replace the file path within the four shell scripts for preparing data. 
After that, you should have a look at and convert your own data to my extracted data format.

As for the fourth step, generating novel captioning dataset, you might have to rewrite it based on your own setup.

**Comment by CherishineNi** [comment]
> @CherishineNi
> 
> Sorry that I did catch the point. Are you going to train a DNOC captioning model on your OWN data?
> 
> To do this, you might first replace the file path within the four shell scripts for preparing data.
> After that, you should have a look at and convert your own data to my extracted data format.
> 
> As for the fourth step, generating novel captioning dataset, you might have to rewrite it based on your own setup.


I want to train a DNOC captioning model on my OWN data. But I don't konw how to convert my own data to your extracted data format.

**Comment by Yu-Wu** [comment]
@CherishineNi 
You can have a look at the provided extracted feature and try to convert yours to its shape.

**Comment by CherishineNi** [comment]
> @CherishineNi
> You can have a look at the provided extracted feature and try to convert yours to its shape.

Sorry, I want to download  the pre-extracted detection results  via Google Drive.But it is to big, I can't download. Do you have any ideas?

**Comment by Yu-Wu** [comment]
@CherishineNi 

You may try the following link, which is a single file example of the extracted detection result.

https://drive.google.com/open?id=1lhjNW7CNi9-Pq28vt41C4I-ll1oHl0mI


In the 'extracted_object_memory' folder, there are 123,287 extracted files that are similar to the provided example. Each one corresponds to one image in the COCO dataset.

**Comment by CherishineNi** [comment]
Thank you very much! Another way, could you upload it to cloud disk for me to download? Because I am in China, it is difficult for me to connect the Google to download it.

**Comment by Yu-Wu** [comment]
@CherishineNi 

I uploaded it to the BaiduYun Disk. Please check the following link:
https://pan.baidu.com/s/189DIu1oDZV7pOYEjcBw4JA

**Comment by Yu-Wu** [comment]
@CherishineNi 
I am sorry that I can not upload the whole detection feature file (5 GB) to BaiduYun (over the size limit).

**Comment by CherishineNi** [comment]
> @CherishineNi
> I am sorry that I can not upload the whole detection feature file (5 GB) to BaiduYun (over the size limit).

Thank you for your reply. Could you tell me how to generate this file 
such as COCO_train2014_000000346521.jpg.npz? And wher is it used?

**Comment by Yu-Wu** [comment]
@CherishineNi 
To generate the detection results, please see this script: 
https://github.com/Yu-Wu/Decoupled-Novel-Object-Captioner/blob/master/prepare_data/step2_detection.sh

To use it, you may check the following scripts and the main training code.
